streams::
	nats s create chat_messages --subjects "chat.>" --defaults
	nats kv add chat_workspace
	cat jeremy.json | nats kv put chat_workspace users.amVyZW15QHN5bmFkaWEuY29t
	cat byron.json | nats kv put chat_workspace users.Ynlyb25Ac3luYWRpYS5jb20=
