CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL UNIQUE,
  timezone TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_time_customers
  BEFORE UPDATE 
  ON customers
  FOR EACH ROW
BEGIN 
  UPDATE customers SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id; 
END;
